### PR TITLE
Privileges/permissions

### PR DESCRIPTION
**Pull request by dgilge**
Decisions to make:

- Do we use an automated system (privileges are assigend according to reputation) or a community system (users assign privileges)? - We decided to use an automated, score-based system.

### CODE REVIEW

**Comment by dgilge** [comment]
Some notes on the privileges:

- What does it mean to *flag*? I think when you normally flag something the maintainer will be informed about abuse but users won't see a "flag".
- I'd rename *upvote* because you might think of an optional voting (in case you really like it). But these upvotes are requried for completion of the translation. So maybe *confirm* was better?
- What do you mean by *hide*?

**Comment by lhermann** [comment]
Use a numbered list, it's easier to answer:

1.  *flag* is correct, maintainer/admin gets informed, user doesn't know until maintainer intervenes
2. it's okay to rename *upvote*. I think *approve* is more appropriate.
3. *hide* means an inappropriate comment will not be visible anymore. In many chats/comment threads it show up like ```Lukas: [comment was hidden bei maintainer]```, which is useful for inappropriate comments, but `delete` may serve the same purpose.

**Comment by dgilge** [comment]
Ok. I think it's important to use commonly understood terms. This is why I have these questions...

(Numberd list doesn't reflect your numbering.)

1. GitHub calls *flag* *report*. This might be even better.
3. Is *hide* and *delete* a difference in our design? What if the poster wants to delete it? Is it then removed completely (like on GitHub)?
4. Is *rollback* a common term for this purpose? Or is *restore*, *redo*, *recover* or *undo* better?

**Comment by lhermann** [comment]
1. *report* is probably clearer.
2. *hide* and *delete* is different. If commenter or admin deletes a comment, it's gone from the database. If he hides it, it will still be there, but the content is not visible (this is somethimes better for usability reasons, so the original commenter doesn't think his comment was lost or something)
3. *rollback* is a developer term. I am using the word *restore* in the UI, I think it will be clearer to our target group.

**Comment by dgilge** [comment]
1. Then I'll call it *restore* in the backend, too. Any objection?
2. What about deleting a translation? *Can delete translations = 150*

**Comment by lhermann** [comment]
*delete translation* is really just an edit that removes all the text. Or do you mean removing a `history object`? In this case we should handle it like git, that deleting is not possible ... except, again, for content with unclean language.

**Comment by dgilge** [comment]
Ha, deleting historical records... That gets interesting. I think we'll come back to that later.

But I was actually refering to segments. Yes, deletion of a translation is actually just removing the text with one difference: I'd say it always creates an own historical record (which hasn't any text, but another change reason). I think it's not so easy to implement it if we don't have a separate API endpoint for deletion (which is implemented already) using the current segment and history handling.

But after all it's your task to make the UI and if you don't see a fitting place for deletion I can remove the endpoint.

Restoring also always produces it's own historical record, doesn't it?

**Comment by dgilge** [comment]
Why should *flagging* require such high reputation if users don't see it? I mean actually everybody should be albe to report abuse... And I think it should cost a lot more than 5 points. I mean you risk your account when you abuse the platform.

**Comment by dgilge** [comment]
I like *approve* but what I didn't think of is *downvote*. If we change *upvote* we should change *downvote*, too. What about *disapprove* or *decline*?

**Comment by lhermann** [comment]
> Yes, deletion of a translation is actually just removing the text with one difference: I'd say it always creates an own historical record

That's what I meant

> Restoring also always produces it's own historical record, doesn't it?

Yes

> I mean actually everybody should be albe to report abuse

Good point, I think you are right

> What about disapprove or decline?

*disapprove*, then it is consistent

**Comment by dgilge** [comment]
Thanks for your quick responses @lhermann . I've updated the document to reflect our discussions.

I kept *flag* because *can report comment* might not be specific enough.

I'm not sure how much permissions trustees and repsonsible entities should have... Right now only the reputation counts. But we probably should change that.

**Comment by lhermann** [comment]
Great! So you can can merge.

Permissions for trustees is a separate issue

**Comment by lhermann** [comment]
One more thing:

`-1   | Another version is restored`

We probably want to specify that to avoid punishing "innocent" people with every restore. Maybe only limit this penalty to an action restoring particularly the edits of one person. as in: E`dit A - Edit B - Restore A` --> B gets penalty

Alternatively: `Edit A - Edit B - Edit C - Edit D - Restore A` --> B, C and D get penalty

And what if the restored version gets restored? `Edit A - Edit B - Restore A - Restore B`?

**Comment by dgilge** [comment]
> So you can can merge.

I actually wanted to discuss much more in this PR, especially score details.

> `Edit A - Edit B - Edit C - Edit D - Restore A` --> B, C and D get penalty

I agree doing it that way.

> And what if the restored version gets restored?

We should restore the reputation, too.

**Comment by lhermann** [comment]
I imagine the whole restoring of reputation can get quite complicated, doesn't it? But it's your part :)

Sure, go ahead, what other points should we tackle?

**Comment by lhermann** [comment]
Yes, we should

**Comment by lhermann** [comment]
great! You can merge now.

**Comment by dgilge** [comment]
I merge this now to be able to do our homework. ;)

**Comment by lhermann** [comment]
And you merged it right into master ... so then we have to merge from master back into staging I guess.

**Comment by dgilge** [comment]
There is no staging in this repo ;)

**Pull request merged**
